package com.myapp.tabbed;

import com.formdev.flatlaf.FlatDarculaLaf;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author RAVEN
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialTabbed1 = new MaterialTabbed();
        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        jPanel3 = new JPanel();
        jPanel4 = new JPanel();
        jPanel5 = new JPanel();

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();


        Color BGColor = new FlatDarculaLaf().getDefaults().getColor(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        /**
         * JPanel1
         */
        setPanelBackground(jPanel1, BGColor);

        materialTabbed1.setFont(new Font("sanserif", 1, 10)); // NOI18N
        //materialTabbed1.setSelectedColor(new Color(63, 250, 0));
        //materialTabbed1.setUnselectedColor(new Color(0, 62, 255));

        /**
         * JPanel2
         * JLabel1
         */
        setPanelBackground(jPanel2, BGColor);
        setLabel(jLabel1, "Tabbed 1");
        setLayout(jPanel2, jLabel1);
        addTab(materialTabbed1, jPanel2, "Home");

        /**
         * JPanel3
         * JLabel2
         */
        setPanelBackground(jPanel3, BGColor);
        setLabel(jLabel2, "Tabbed 2");
        setLayout(jPanel3, jLabel2);
        addTab(materialTabbed1, jPanel3, "Product");

        /**
         * JPanel4
         * JLabel3
         */
        setPanelBackground(jPanel4, BGColor);
        setLabel(jLabel3, "Tabbed 3");
        setLayout(jPanel4, jLabel3);
        addTab(materialTabbed1, jPanel4, "User");

        /**
         * JPanel5
         * JLabel4
         */
        setPanelBackground(jPanel5, BGColor);
        setLabel(jLabel4, "Tabbed 4");
        setLayout(jPanel5, jLabel4);
        addTab(materialTabbed1, jPanel5, "Staff");

        /**
         * JPanel1
         * JLabel2
         */
        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(materialTabbed1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(materialTabbed1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );


        /**
         * Layout
         */
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setLayout(JPanel jPanel, JLabel jLabel) {
        GroupLayout jPanelLayout = new GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
                jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel, GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
                jPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel, GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }

    private void addTab(MaterialTabbed materialTabbed, JPanel panel, String tabName){
        materialTabbed.addTab(tabName, panel);
    }

    private void setPanelBackground(JPanel panel, Color color){
        panel.setBackground(color);
    }

    private void setLabel(JLabel jLabel, String tabName) {
        jLabel.setFont(new Font("sanserif", 1, 18)); // NOI18N
        jLabel.setForeground(new Color(220, 220, 220));
        jLabel.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel.setText(tabName);
    } // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private MaterialTabbed materialTabbed1;
    // End of variables declaration//GEN-END:variables
}